// Generated by scripts/sync-shared.mjs from shared/client/sanbao-tokens.ts. Do not edit this copy; edit the shared source and run "node scripts/sync-shared.mjs".
/**
 * 品牌 token 源 `--sanbao-*`（S-B，色值唯一可编辑面）。
 *
 * 键名逐条对照供体契约（WorldPilot `website/src/styles.css` 的 body.v1 色板
 * 十键、`--metal-*` 材质七项、`--ux-*` 动效四项），名字空间改为 `--sanbao-*`。
 *
 * 002 骨架期值 = 现状（LUTE 绿主题），且**没有任何消费面被接线**——改动本模块
 * 无行为效果。填值策略：
 * - 现状有字面值的键 → 填字面值（出处注明，来自 theme-settings.ts 的
 *   DEFAULT_THEME_STUDIO_SETTINGS，即新装默认读数）；
 * - 现状由别名计算得出的键 → 引用既有 `--dsw-alias-*`（随主题自动翻转）；
 * - 现状不存在的键（材质、动效家族）→ 占位值 + 注记，接线前惰性。
 * 亮暗两态用本仓既有约定：`:root` 亮 / `body[data-ds-dark-theme]` 暗。
 *
 * `theme-tokens` 门禁的 NAMESPACE 本张不扩——扩列必须与真实值迁移同片
 * （工单 002 验收标准）；此前引用未定义的 `--sanbao-*` 不会被门禁判红。
 *
 * 经 `scripts/sync-shared.mjs` 分发（副本首行带生成标记）；改这里后跑
 * `node scripts/sync-shared.mjs --write`。
 */

export const SANBAO_TOKEN_CSS = `:root {
  /* 色板十键。现状字面出处：packages/platform/dsh-theme-local/src/theme-settings.ts */
  --sanbao-bg: #F6F7F4;
  --sanbao-surface: #FFFFFF;
  --sanbao-surface2: var(--dsw-alias-bg-layer-2);
  --sanbao-ink: #1E221F;
  --sanbao-muted: var(--dsw-alias-label-secondary);
  --sanbao-line: var(--dsw-alias-border-l2);
  --sanbao-good: var(--dsw-alias-state-success-primary);
  --sanbao-accent: #347A2F;
  /* 现状无独立 on-accent token（官方引擎内联决定按钮文字色）；S1 落供体字面 */
  --sanbao-on-accent: var(--dsw-alias-label-primary);
  /* 现状圆角基线 = 本仓 --lute-radius-row */
  --sanbao-radius: var(--lute-radius-row);

  /* 材质七项（供体 --metal-*）。现状无材质语言，平色/透明占位；S1 换双色道 */
  --sanbao-metal-ink: var(--dsw-alias-label-primary);
  --sanbao-metal-border: var(--dsw-alias-border-l2);
  --sanbao-metal-shadow: transparent;
  --sanbao-metal-fill: var(--dsw-alias-bg-layer-1);
  --sanbao-metal-line: var(--dsw-alias-border-l2);
  --sanbao-metal-highlight: transparent;
  --sanbao-metal-pressed: transparent;

  /* 动效四项（供体 --ux-*）。现状无统一动效 token 家族，接线前惰性 */
  --sanbao-fast: 160ms;
  --sanbao-base: 260ms;
  --sanbao-slow: 520ms;
  --sanbao-ease: cubic-bezier(.22,1,.36,1);
}

body[data-ds-dark-theme] {
  --sanbao-bg: #171A17;
  --sanbao-surface: #202420;
  --sanbao-ink: #F1F4F0;
  --sanbao-accent: #58B848;
}`

/** 注入 style 标签的 data 锚（幂等判据，也是浏览器探针可观察的自报面）。 */
const STYLE_ANCHOR = 'sanbaoTokens'

/**
 * 幂等注入 `--sanbao-*` token（与 ensureLuteTokens 同一形状）。
 *
 * 判据是 style 标签上的 data 锚而不是文本比对；调用方不得在 dispose 时移除
 * 这个标签。002 骨架期没有调用方——本函数随接缝一起立形状，接线由换值工单做。
 * @returns 注入的标签（本次未注入时返回既有标签；无 document 时返回 undefined）。
 */
export function ensureSanbaoTokens(): HTMLStyleElement | undefined {
  if (typeof document === 'undefined') return undefined
  const existing = document.querySelector<HTMLStyleElement>(`style[data-sanbao-tokens="${STYLE_ANCHOR}"]`)
  if (existing !== null) return existing
  const style = document.createElement('style')
  style.dataset.sanbaoTokens = STYLE_ANCHOR
  style.textContent = SANBAO_TOKEN_CSS
  document.head.append(style)
  return style
}
