// Generated by scripts/sync-shared.mjs from shared/client/sanbao-tokens.ts. Do not edit this copy; edit the shared source and run "node scripts/sync-shared.mjs".
/** Fixed semantic palette. All product color literals live here; dsw is a projection only. */
export const THEME_IDS = ["light", "dark", "warm-pink"] as const;
export type ThemeId = (typeof THEME_IDS)[number];
export function themeColorScheme(id: ThemeId): "light" | "dark" {
  return id === "dark" ? "dark" : "light";
}
export const SANBAO_PALETTES = Object.freeze({
  light: Object.freeze({
    canvas: "#FDFDFD", sidebar: "#F1F1F0", rightSidebar: "#F6F6F6", panel: "#FFFFFF",
    inset: "#F6F6F6", overlay: "#FFFFFF", foreground: "#202120", secondary: "#60635E",
    accent: "#386940", accentFill: "#386940", onAccent: "#FFFFFF", hover: "#E9EBE7",
    pressed: "#DDE3DC", selected: "#E4ECE4", disabled: "#959A93", border: "#D7DBD4",
    controlBorder: "#788076", success: "#2F6B3D", warning: "#855D18", error: "#A94040",
  }),
  dark: Object.freeze({
    canvas: "#232523", sidebar: "#242624", rightSidebar: "#191B1A", panel: "#191B1A",
    inset: "#131413", overlay: "#131413", foreground: "#ECEDEB", secondary: "#AFB5AF",
    accent: "#8FBC99", accentFill: "#5C9363", onAccent: "#101C12", hover: "#2E332F",
    pressed: "#343C35", selected: "#293A2D", disabled: "#737D75", border: "#3E463F",
    controlBorder: "#818E84", success: "#8FBC99", warning: "#DAB879", error: "#E49393",
  }),
  "warm-pink": Object.freeze({
    canvas: "#FFF8F7", sidebar: "#F7EEEC", rightSidebar: "#F7EEEC", panel: "#FFFDFC",
    inset: "#F3E6E4", overlay: "#FFFDFC", foreground: "#382E30", secondary: "#6B595E",
    accent: "#874958", accentFill: "#8F5361", onAccent: "#FFFFFF", hover: "#EFE1DF",
    pressed: "#E9D8D6", selected: "#EDDBDE", disabled: "#A48F94", border: "#DCC8CD",
    controlBorder: "#91717B", success: "#406748", warning: "#80501F", error: "#A53945",
  }),
});
export type PaletteKey = keyof typeof SANBAO_PALETTES.light;
const kebab = (key: string) => key.replace(/[A-Z]/g, letter => `-${letter.toLowerCase()}`);
/** Body-scoped variables are also consumed by the real settings-card previews. */
export function buildSanbaoVariables(id: ThemeId): Record<string, string> {
  return Object.fromEntries(Object.entries(SANBAO_PALETTES[id]).map(([key, value]) => [`--sanbao-${kebab(key)}`, value]));
}
const COMPATIBILITY_VARIABLES = {
  bg: "canvas", surface: "panel", surface2: "inset", ink: "foreground", muted: "secondary",
  line: "border", good: "success", "metal-ink": "foreground", "metal-border": "border",
  "metal-fill": "panel", "metal-line": "border", "metal-highlight": "hover", "metal-pressed": "pressed",
} as const;
function declarations(id: ThemeId): string {
  return Object.entries(buildSanbaoVariables(id)).map(([key, value]) => `${key}: ${value};`).join("\n  ");
}
export const SANBAO_TOKEN_CSS = `body {
  ${Object.entries(COMPATIBILITY_VARIABLES).map(([key, value]) => `--sanbao-${key}: var(--sanbao-${value});`).join("\n  ")}
  --sanbao-radius: var(--lute-radius-row, 8px);
  --sanbao-metal-shadow: transparent;
  --sanbao-success-surface: color-mix(in srgb, var(--sanbao-success) 10%, var(--sanbao-canvas));
  --sanbao-warning-surface: color-mix(in srgb, var(--sanbao-warning) 10%, var(--sanbao-canvas));
  --sanbao-error-surface: color-mix(in srgb, var(--sanbao-error) 10%, var(--sanbao-canvas));
  --sanbao-fast: 160ms;
  --sanbao-base: 260ms;
  --sanbao-slow: 520ms;
  --sanbao-ease: cubic-bezier(.22,1,.36,1);
}
body:not([data-sanbao-theme]) { ${declarations("light")} }
body[data-ds-dark-theme]:not([data-sanbao-theme]) { ${declarations("dark")} }
${THEME_IDS.map(id => `body[data-sanbao-theme="${id}"] {\n  color-scheme: ${themeColorScheme(id)};\n  ${declarations(id)}\n}`).join("\n")}`;

/** Acquire the shared sheet; release only removes a sheet created by this module. */
const sheets = new WeakMap<Document, { tag: HTMLStyleElement; users: number; owned: boolean }>();
export function ensureSanbaoTokens(doc: Document = document): () => void {
  let sheet = sheets.get(doc);
  if (!sheet) {
    const existing = doc.querySelector<HTMLStyleElement>('style[data-sanbao-tokens]');
    const tag = existing ?? doc.createElement("style");
    tag.dataset.sanbaoTokens = "sanbaoTokens";
    tag.textContent = SANBAO_TOKEN_CSS;
    if (!existing) doc.head.append(tag);
    sheet = { tag, users: 0, owned: !existing };
    sheets.set(doc, sheet);
  }
  sheet.users++;
  let released = false;
  return () => {
    if (released) return;
    released = true;
    if (--sheet.users === 0) {
      if (sheet.owned) sheet.tag.remove();
      sheets.delete(doc);
    }
  };
}
