import type { ThemeTokenOverrides } from "@deepseek-ai/dsh-client-ui-theme/client";
import type { ThemeStudioSettings } from "../theme-settings.js";
import { buildThemeTypography } from "./theme-typography.js";

function same(value: string) { return { light: value, dark: value }; }

export function buildThemeTokenOverrides(settings: ThemeStudioSettings): ThemeTokenOverrides {
  return {
    ...buildThemeTypography(settings),
    "--dsw-alias-bg-base": same("var(--sanbao-canvas)"),
    "--dsw-alias-bg-layer-1": same("var(--sanbao-panel)"),
    "--dsw-alias-button-elevated-fill": same("var(--sanbao-panel)"),
    "--dsw-alias-button-floating-fill": same("var(--sanbao-panel)"),
    "--dsw-alias-button-tool-bar-fill": same("var(--sanbao-panel)"),
    "--dsw-specific-menu": same("var(--sanbao-panel)"),
    "--dsw-specific-selector": same("var(--sanbao-panel)"),
    "--dsw-alias-bg-layer-3": same("var(--sanbao-overlay)"),
    "--dsw-alias-bg-overlay": same("var(--sanbao-overlay)"),
    "--dsw-alias-toast-bg": same("var(--sanbao-overlay)"),
    "--dsw-alias-tooltip-bg": same("var(--sanbao-overlay)"),
    "--dsw-specific-tip": same("var(--sanbao-overlay)"),
    "--dsw-alias-bg-layer-2": same("var(--sanbao-inset)"),
    "--dsw-alias-bg-module-platform": same("var(--sanbao-inset)"),
    "--dsw-alias-markdown-inline-code": same("var(--sanbao-inset)"),
    "--dsw-alias-markdown-code-block": same("var(--sanbao-inset)"),
    "--dsw-alias-markdown-code-block-banner": same("var(--sanbao-inset)"),
    "--dsw-alias-markdown-code-segment-unselected": same("var(--sanbao-inset)"),
    "--dsw-specific-input-major": same("var(--sanbao-inset)"),
    "--dsw-specific-login-input": same("var(--sanbao-inset)"),
    "--dsw-specific-sidebar-fill": same("var(--sanbao-sidebar)"),
    "--dsw-specific-sidebar-right-fill": same("var(--sanbao-right-sidebar)"),
    "--dsw-alias-label-primary": same("var(--sanbao-foreground)"),
    "--dsw-alias-label-primary-bluish": same("var(--sanbao-foreground)"),
    "--dsw-alias-label-secondary": same("var(--sanbao-secondary)"),
    "--dsw-alias-label-tertiary": same("var(--sanbao-secondary)"),
    "--dsw-alias-label-caption": same("var(--sanbao-secondary)"),
    "--dsw-alias-markdown-placeholder": same("var(--sanbao-secondary)"),
    "--dsw-alias-label-dimmed": same("var(--sanbao-disabled)"),
    "--dsw-alias-label-primary-dimmed": same("var(--sanbao-disabled)"),
    "--dsw-alias-button-primary-dimmed": same("var(--sanbao-disabled)"),
    "--dsw-alias-bg-skeleton": same("var(--sanbao-disabled)"),
    "--dsw-alias-scrollbar-bg-l1": same("var(--sanbao-disabled)"),
    "--dsw-alias-scrollbar-bg-l2": same("var(--sanbao-disabled)"),
    "--dsw-alias-brand-primary": same("var(--sanbao-accent)"),
    "--dsw-alias-brand-text": same("var(--sanbao-accent)"),
    "--dsw-alias-brand-primary-invert": same("var(--sanbao-accent)"),
    "--dsw-alias-brand-primary-new-colorprimary-new-color": same("var(--sanbao-accent)"),
    "--dsw-alias-state-business-primary": same("var(--sanbao-accent)"),
    "--dsw-alias-link": same("var(--sanbao-accent)"),
    "--dsw-static-deepseek-500": same("var(--sanbao-accent)"),
    "--dsw-static-deepseek-450": same("var(--sanbao-accent)"),
    "--dsw-static-deepseek-200": same("var(--sanbao-accent)"),
    "--dsw-alias-button-info-fill": same("var(--sanbao-accent-fill)"),
    "--dsw-alias-button-info-hover": same("var(--sanbao-accent-fill)"),
    "--dsw-alias-button-primary-fill": same("var(--sanbao-accent-fill)"),
    "--dsw-alias-button-primary-hover": same("var(--sanbao-accent-fill)"),
    "--dsw-alias-button-contrast-fill": same("var(--sanbao-accent-fill)"),
    "--dsw-alias-label-primary-inverted": same("var(--sanbao-on-accent)"),
    "--dsw-alias-label-primary-foreground": same("var(--sanbao-on-accent)"),
    "--dsw-alias-interactive-bg-hover": same("var(--sanbao-hover)"),
    "--dsw-alias-interactive-bg-hover-solid": same("var(--sanbao-hover)"),
    "--dsw-alias-interactive-bg-hover-accent": same("var(--sanbao-hover)"),
    "--dsw-specific-sidebar-nav-item-hover": same("var(--sanbao-hover)"),
    "--dsw-alias-button-floating-hover": same("var(--sanbao-hover)"),
    "--dsw-alias-button-tool-bar-hover": same("var(--sanbao-hover)"),
    "--dsw-alias-button-ghost-active-hover": same("var(--sanbao-hover)"),
    "--dsw-alias-interactive-bg-active": same("var(--sanbao-pressed)"),
    "--dsw-specific-sidebar-nav-item-active": same("var(--sanbao-pressed)"),
    "--dsw-specific-bubble-highlight": same("var(--sanbao-pressed)"),
    "--dsw-alias-bg-multi-select": same("var(--sanbao-selected)"),
    "--dsw-specific-bubble": same("var(--sanbao-selected)"),
    "--dsw-specific-sidebar-nav-item-active-accent": same("var(--sanbao-selected)"),
    "--dsw-alias-state-business-tertiary": same("var(--sanbao-selected)"),
    "--dsw-alias-markdown-code-segment-selected": same("var(--sanbao-selected)"),
    "--dsw-alias-markdown-citation": same("var(--sanbao-selected)"),
    "--dsw-alias-markdown-tag": same("var(--sanbao-selected)"),
    "--dsw-alias-button-ghost-active-fill": same("var(--sanbao-selected)"),
    "--dsw-alias-border-l1": same("var(--sanbao-border)"),
    "--dsw-alias-border-l2": same("var(--sanbao-border)"),
    "--dsw-alias-border-l2-darkmode-thin": same("var(--sanbao-border)"),
    "--dsw-alias-border-inverted": same("var(--sanbao-border)"),
    "--dsw-alias-border-inverted2": same("var(--sanbao-border)"),
    "--dsw-alias-border-l3": same("var(--sanbao-control-border)"),
    "--dsw-alias-border-l4": same("var(--sanbao-control-border)"),
    "--dsw-alias-button-ghost-active-border": same("var(--sanbao-control-border)"),
    "--dsw-alias-scrollbar-hover-l1": same("var(--sanbao-control-border)"),
    "--dsw-alias-scrollbar-hover-l2": same("var(--sanbao-control-border)"),
    "--dsw-alias-state-success-primary": same("var(--sanbao-success)"),
    "--dsw-alias-state-warn-primary": same("var(--sanbao-warning)"),
    "--dsw-alias-state-warn-label": same("var(--sanbao-warning)"),
    "--dsw-alias-state-error-primary": same("var(--sanbao-error)"),
    "--dsw-alias-state-success-secondary": same("var(--sanbao-success-surface)"),
    "--dsw-alias-state-success-tertiary": same("var(--sanbao-success-surface)"),
    "--dsw-alias-state-warn-secondary": same("var(--sanbao-warning-surface)"),
    "--dsw-alias-state-warn-tertiary": same("var(--sanbao-warning-surface)"),
    "--dsw-alias-state-error-secondary": same("var(--sanbao-error-surface)"),
    "--dsw-alias-interactive-bg-hover-danger": same("var(--sanbao-error-surface)"),
  };
}
